[versions]

tomlj = "1.1.1"

axion-release-plugin = "1.21.0"

junit = "6.0.1"
junit-platform = "6.0.0"
mockk = "1.14.6"

jacoco = "0.8.14"
testkit-jacoco-plugin = "1.0.4"
gradle-plugin-publish = "2.0.0"

[libraries]

tomlj = { group = "org.tomlj", name = "tomlj", version.ref = "tomlj" }

jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[bundles]

[plugins]

axion-release-plugin = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release-plugin" }

testkit-jacoco-plugin = { id = "io.github.gmazzo.gradle.testkit.jacoco", version.ref = "testkit-jacoco-plugin" }

gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
