name: PoVerCat Release

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_WRITE_KEY }}" > ~/.ssh/deploy_key_rsa
          chmod 600 ~/.ssh/deploy_key_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git to use SSH
        run: |
          git config --global user.name "release-bot"
          git config --global user.email "release-bot@noreply.github.com"
          git remote set-url origin git@github.com:the13haven/povercat-plugin.git

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Build Sources
        run: ./gradlew build --no-daemon

      - name: Perform Release
        id: release
        run: ./gradlew release -Prelease.customKeyFile="$HOME/.ssh/deploy_key_rsa" -Prelease.customKeyPassword=""

      - name: Publish to Gradle Plugin Portal
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

#      - name: Publish Packages
#        run: ./gradlew publish -Ppublish.username=${{ github.actor }} -Ppublish.token=${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Marker
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASED_VERSION: ${{ steps.release.outputs.released-version }}
        run: |
          gh release create "v$RELEASED_VERSION" \
                    --title "v$RELEASED_VERSION" \
                    --generate-notes